<a href="https://colab.research.google.com/github/a-forty-two/COG-02082021/blob/main/COG_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

input = np.array([1,2,3,4,5])
print(input)
print(input.ndim)

[[1 2 3 4 5]]
2


In [13]:
import numpy as np

input = np.array([[[1,2,3,4,5],[11,2,31,4,51],[12,33,6,35,78]],[[1,2,3,4,5],[11,2,31,4,51],[12,33,6,35,78]]])
print(input)
print(input.ndim)
print(input.shape)

[[[ 1  2  3  4  5]
  [11  2 31  4 51]
  [12 33  6 35 78]]

 [[ 1  2  3  4  5]
  [11  2 31  4 51]
  [12 33  6 35 78]]]
3
(2, 3, 5)


In [9]:
data = [1,2,3,45,6]
print(data)


[1, 2, 3, 45, 6]


In [16]:
input = np.array([1,2,3,4,5])
xFiltr = [True,False,True,False,True]
output = input[xFiltr]
print(output)

[1 3 5]


In [18]:
import pandas as pd

data = pd.Series([1,4,7,np.NaN,9])
data

0    1.0
1    4.0
2    7.0
3    NaN
4    9.0
dtype: float64

In [19]:
dates = pd.date_range('20210101', periods=6)
dates

DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
               '2021-01-05', '2021-01-06'],
              dtype='datetime64[ns]', freq='D')

In [21]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
df

A         B         C         D
2021-01-01 -0.416052 -0.240987  0.666859 -0.102624
2021-01-02 -0.396612 -0.169654 -1.108612  1.733267
2021-01-03 -2.371463  0.572874  1.018449  0.071244
2021-01-04 -0.581882  1.742696 -1.239521 -1.350761
2021-01-05 -0.054876 -1.122202 -0.358099  0.054650
2021-01-06  1.474836 -1.743376 -0.817215 -1.460640