<a href="https://colab.research.google.com/github/a-forty-two/COG-02082021/blob/main/COG_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

input = np.array([1,2,3,4,5])
print(input)
print(input.ndim)

[[1 2 3 4 5]]
2


In [13]:
import numpy as np

input = np.array([[[1,2,3,4,5],[11,2,31,4,51],[12,33,6,35,78]],[[1,2,3,4,5],[11,2,31,4,51],[12,33,6,35,78]]])
print(input)
print(input.ndim)
print(input.shape)

[[[ 1  2  3  4  5]
  [11  2 31  4 51]
  [12 33  6 35 78]]

 [[ 1  2  3  4  5]
  [11  2 31  4 51]
  [12 33  6 35 78]]]
3
(2, 3, 5)


In [9]:
data = [1,2,3,45,6]
print(data)


[1, 2, 3, 45, 6]


In [16]:
input = np.array([1,2,3,4,5])
xFiltr = [True,False,True,False,True]
output = input[xFiltr]
print(output)

[1 3 5]
